In [1]:
import numpy as np

# Slicing

Extract the following slices from `np.arange(0, 20)`:

 * `array([10, 11, 12, 13, 14, 15])`
 * `array([1, 4, 7, 10, 13])`
 * `array([18, 14, 10])`

In [2]:
a = np.arange(0, 20)

In [3]:
a[10:16]

array([10, 11, 12, 13, 14, 15])

In [4]:
a[1:14:3]

array([ 1,  4,  7, 10, 13])

In [5]:
a[18:9:-4]

array([18, 14, 10])

Extract the following slices from `np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])`:

 * `array([[1, 2, 3], [7, 8, 9]])`
 * `array([[1, 3], [4, 6], [7, 9], [10, 12]])`

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [7]:
a[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [8]:
a[:,::2]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

 ## Linear algebra operations
 
 * Implement a function `l2norm` that takes a vector as its argument and returns its $\ell_2$ norm.
 * Implement a function `euclid_dist` that takes two vectors as its arguments and returns the euclidean distance between the vectors.
 * Implement a function `cosine_sim` that takes two vectors as its arguments and returns the cosine similarity between the vectors (cos Θ).
 
**Note:** you can use the `math.sqrt` or `np.sqrt` function for computing the square root. You can use the regular `-` operator for elementwise subtraction of vector components.

In [9]:
def l2norm(v):
    return np.sqrt(v @ v)

l2norm(np.arange(10))

16.881943016134134

In [10]:
def euclid_dist(u, v):
    return l2norm(u - v)
euclid_dist(np.array([2, 0]), np.array([0, 2]))

2.8284271247461903

In [11]:
def cosine_sim(u, v):
    return (u @ v) / (l2norm(u) * l2norm(v))
cosine_sim(np.array([2,1]), np.array([1,2]))

0.79999999999999982

## Broadcasting

Try to sum a tensor of shape `(2, 1, 3)` and a tensor of shape `(2, 3, 1)` elementwise. Explain the result.

In [12]:
a = np.arange(0, 6).reshape((2, 1, 3))
b = np.arange(0, 6).reshape((2, 3, 1))
a + b

array([[[ 0,  1,  2],
        [ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 6,  7,  8],
        [ 7,  8,  9],
        [ 8,  9, 10]]])